### ISSUE TITLE
Develop derived table erm_agreements_package_content_item

### ISSUE THREAD

**Issue by adoerrer** [folio-org/folio-analytics#120]
Creates a derived table on all needed data of the local KB on package_conent_item level

[relation diagram](https://docs.google.com/presentation/d/1kmNMvmFs0-T30X5FqfNNPZuWi6EKazLAbFqyYlg6dD8/edit#slide=id.g9951f7b59d_1_0)

**Comment by nassibnassar** [comment]
Merged to `erm` branch.
