### ISSUE TITLE
Develop derived tables po_lines_mat_type_*

### ISSUE THREAD

**Issue by sbeltaine** [folio-org/folio-analytics#128]
Starting table in FROM is
po_lines

separate derived tables for JSON arrays extracted:
-electronic resources
-material type
-physical resources

Other tables joined
material types

*Material type on the PO has not been developed in the Orders application yet.

**Comment by sbeltaine** [comment]
2 new derived tables were just submitted for this issue:
po_lines_phys_mat_type
po_lines_er_mat_type

**Comment by nassibnassar** [comment]
PR #136

**Comment by nassibnassar** [comment]
What tables remain to be developed for this issue, other than the two that have been submitted?

**Comment by sbeltaine** [comment]
I think we only need the 2 tables, so I that should wrap up this issue
