### ISSUE TITLE
Investigate adding po line id for holdings and items

### ISSUE THREAD

**Issue by sbeltaine** [folio-org/folio-analytics#140]
-There can be multiple items on one purchase order, and not every item is tied to a po line, so the po line identifier needs to be added to inventory items
-Sharon to ask RM PO (Dennis) and Inventory PO (Charlotte) about adding a po line id to the holdings and items tables

**Comment by nassibnassar** [comment]
Is this planned for 1.0 or 1.1?

**Comment by sbeltaine** [comment]
This can be part of 1.1
