### ISSUE TITLE
Correct MM Derived Report Instances-Publication for naming consistency

### ISSUE THREAD

**Issue by jenmawe** [folio-org/folio-analytics#144]
Ensure that the id and hrid have instance in front of these and the names use the property names. If the property name has camel, the name in the column will be that name all lower case and using underscore to separate words.

**Comment by clynnt** [comment]
Updated the naming conventions - table names in the singular, spelled out instance in the id / hrid column names, and removed table name prefixes from column names (inst_pub_).
