### ISSUE TITLE
Correct MM Derived Report Instance_formats for naming consistency

### ISSUE THREAD

**Issue by jenmawe** [folio-org/folio-analytics#148]
Ensure that the id and hrid have instance/item/holdings in front of these and the names use the property names. If the property name has camel, the name in the column will be that name all lower case and using underscore to separate words.

[Link to instance_formats.sql](https://github.com/folio-org/folio-analytics/blob/master/sql/derived_tables/instance_formats.sql)

**Comment by lew235** [comment]
This was was actually already fine.

**Comment by jenmawe** [comment]
@lew235 I saw that there was one change. For instance_format_id, the other column names are all format_{property name}. Since we also decided to leave off instance, item, or holdings when that reference was explicit, I changed this from instance_format_id to format_id. Now you have format_id, format_name and format_source.
