### ISSUE TITLE
Refactor RA/UM claimed returned report query to use derived tables

### ISSUE THREAD

**Issue by amzoss** [folio-org/folio-analytics#188]
[Claimed Returned query](https://github.com/folio-org/folio-analytics/tree/master/sql/report_queries/claimed_returned)
[Claimed Returned JIRA issue in UXPROD](https://issues.folio.org/browse/UXPROD-2020)

**Comment by amzoss** [comment]
Note: waiting on new array extraction #220 for item_notes and instance_publication

**Comment by nassibnassar** [comment]
It looks to me like claimed_returned does not make use of ordinality.  Could you confirm that it is needed for this query?

**Comment by amzoss** [comment]
So, we actually talked about ordinality being potentially useful. It wouldn't be as important for publication dates because those may not even have the correct order and can be reordered manually. For item notes, being able to preserve the order does actually seem like a benefit for this report.

**Comment by nassibnassar** [comment]
Added https://github.com/folio-org/folio-analytics/issues/311 for item_notes
