### ISSUE TITLE
Change array extraction in derived table queries

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#220]
Update all derived table queries to use a lateral cross join for array extraction, for example:
```
SELECT
    id AS instance_id,
    instance_format_ids.data #>> '{}' AS instance_format_id,
    instance_format_ids.ordinality
FROM
    inventory_instances
    CROSS JOIN LATERAL json_array_elements(json_extract_path(data, 'instanceFormatIds'))
        WITH ORDINALITY
        AS instance_format_ids (data);
```
The old method without a cross join apparently may trigger a bug in Postgres in rare cases.

Queries affected include these derived tables:
```
instance_editions
instance_formats
instance_series
instance_subjects
po_lines_physical
users_departments_unpacked
```

Some report queries are also affected, but that may be because they have not yet been refactored using the derived tables:
```
claimed_returned
pick_list
pick_list_rs
acrl_title_count
```

**Comment by nassibnassar** [comment]
Submitted PRs for all except pick_list and acrl_title_count, which may need to be refactored.  Also claimed_returned may need to be refactored.

**Comment by amzoss** [comment]
Need to complete this for [item_notes](https://github.com/folio-org/folio-analytics/blob/main/sql/derived_tables/item_notes.sql) and [instance_publication](https://github.com/folio-org/folio-analytics/blob/main/sql/derived_tables/instance_publication.sql) before claimed_returned refactor #188 can be finalized.

**Comment by nassibnassar** [comment]
Looking at this more closely, I think the intention of this issue was to use a join to avoid triggering a bug in Postgres.  Adding ordinality is incidental; there are many array extraction queries missing ordinality and it can be added without breaking anything.  I will create another issue for item_notes and instance_publication.
