### ISSUE TITLE
Create MM-Shelf List Report

### ISSUE THREAD

**Issue by jenmawe** [folio-org/folio-analytics#224]
There is the shelf list cluster. See [MM working spreadsheet](https://docs.google.com/spreadsheets/d/1QjYa7zy77Ctiys-5MPj70EWqMluSAOnE3b66UH5pnFY/edit#gid=889298050). [UXPROD-2051](https://issues.folio.org/browse/UXPROD-2051?jql=text%20~%20%22Cluster%22%20AND%20%22Report%20Functional%20Area(s)%22%20%3D%20%22Metadata%20Management%22)

**Comment by nassibnassar** [comment]
I will test this on a live database.
