### ISSUE TITLE
Clean up readme files and subdirectories of report_queries

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#279]
Do the top level readme files need to be updated/pruned?  How will we maintain them?

Also consider moving report queries that have not yet been refactored to a `deprecated/` subdirectory.

**Comment by jenmawe** [comment]
I see 2 reports that need to be pruned.

[pick list redshift version](https://github.com/folio-org/folio-analytics/blob/main/sql/report_queries/pick_list/pick_list_rs.sql)

and

the [HathiTrust](https://github.com/folio-org/folio-analytics/tree/main/sql/report_queries/hathitrust_print)
This HathiTrust report (if I remember correctly) isn't quite working. This was way before our derived tables. I'm working on a new iteration completely.

**Comment by amzoss** [comment]
For RA/UM, I think we'll want to move out both recalls and requests
