### ISSUE TITLE
Missing indexes in loans_items

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#327]
Most of the columns in derived table [loans_items](https://github.com/folio-org/folio-analytics/blob/main/sql/derived_tables/loans_items.sql) do not appear to be indexed.

**Comment by amzoss** [comment]
Here's a version with indexes (indices?), in case it's helpful. I don't want to commit to my current fork and mess up the PR.
[loans_items.sql.zip](https://github.com/folio-org/folio-analytics/files/5894852/loans_items.sql.zip)
