### ISSUE TITLE
Use half-open interval for date range in orders

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#333]
For consistency, the query https://github.com/folio-org/folio-analytics/blob/main/sql/report_queries/orders/orders.sql should probably use
```
OR pol.pol_subscription_from < (
    SELECT
        subscription_to_date
```
instead of
```
OR pol.pol_subscription_from <= (
    SELECT
        subscription_to_date
```

**Comment by sbeltaine** [comment]
Submitted PR to make this change.

**Comment by nassibnassar** [comment]
@sbeltaine Can this issue be closed?

**Comment by sbeltaine** [comment]
Yes. The query has be updated.
