### ISSUE TITLE
Add 'createdDate' to derived table 'instance_ext'

### ISSUE THREAD

**Issue by lib-eric** [folio-org/folio-analytics#372]
Reference: [instance_ext.sql](https://github.com/folio-org/folio-analytics/blob/stable/sql/derived_tables/instance_ext.sql)

The element 'catalogedDate' does not appear to be set automatically:
`json_extract_path_text(instance.data, 'catalogedDate') AS cataloged_date,`

I think it would be useful to also add the calculated field 'createdDate' that is also included in item_ext and holdings_ext:
`json_extract_path_text(instance.data, 'metadata','createdDate') AS created_date,`

We have some cleanup reports that look for records added in the past x days and this reliable date field would be useful.

**Comment by amzoss** [comment]
I'd like to request that the metadata createdDate field have a name that clarifies that it is the createdDate for the instance record itself, and not the instance it refers to. Maybe record_created_date or metadata_created_date.

**Comment by nassibnassar** [comment]
For all of the fields under `metadata`, I am never sure if they are considered part of the business logic.  They appear to be lower-level data, and I usually suggest checking with the PO or developer to confirm how they are updated.  For example, what is `createdDate` set to when a record is imported?

**Comment by lib-eric** [comment]
I was able to find what I think is some documentation:
[PUT /instance-storage/instances/{instanceId}](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/instance-storage.html#instance_storage_instances__instanceid__put)
Metadata:
> "Metadata about creation and changes to records, provided by the server (client should not provide)"

Metadata > createdDate:
> "createdDate": { ...  "description": "Date and time when the record was created" ...

For catalog date:
> "catalogedDate": { ... "description": "Date or timestamp on an instance for when is was considered cataloged" ...

**Comment by nassibnassar** [comment]
That is basically what I wondered about - it looks like low-level metadata for auditing, generated by the server, rather than part of the record proper.  So what I mean is, just be sure that the data there will always be what you expect.

**Comment by jenmawe** [comment]
This is already an issue to enhance the instance_ext derived table. issue #359

**Comment by jenmawe** [comment]
This was already added.
