### ISSUE TITLE
Derived table holdings_ext fails to build if no ILL policies

### ISSUE THREAD

**Issue by wafschneider** [folio-org/folio-analytics#392]
In a system with no defined ILL policies, the `folio_reporting.holdings_ext` table fails to build with this error:
```
ERROR:  column holdings_ill_policy.name does not exist
LINE 40:     holdings_ill_policy.name AS ill_policy_name,
```
"LINE 40" above is a little misleading, in the actual file it is [line 45](https://github.com/folio-org/folio-analytics/blob/db6583d380cce4a5dbca22b58127b3279ff04f97/sql/derived_tables/holdings_ext.sql#L45)

**Comment by nassibnassar** [comment]
@wafschneider Which version or branch are you using?

**Comment by nassibnassar** [comment]
I will label this as a bug since holdings_ext is probably useful even without ILL data.  It looks like the standard workaround using `json_extract_path_text()` will fix this.  We should make a PR for the release-1.0 branch and I will apply it to main as well.
