### ISSUE TITLE
RA/UM - update users_groups to use correct dates

### ISSUE THREAD

**Issue by amzoss** [folio-org/folio-analytics#490]
Change to derived table users_groups: pull created date and updated date from metadata object in users_users since top-level fields are deprecated

**Comment by amzoss** [comment]
Moving out of Lotus since this for the LDP version of the derived table

**Comment by amzoss** [comment]
@eliana-flo for your consideration, maybe loop this change into at least the metadb version of user_groups?

**Comment by eliana-flo** [comment]
@amzoss It looks like the change was already made for the LDP version if I'm not mistaken. Is the created_date and updated_date in **users__t** coming from the metadata object or the top-level fields? I still see both in the jsonb of **users**, so I'm not sure what "deprecated" means here"

**Comment by amzoss** [comment]
So, this came about because we noticed that the top-level fields "createdDate" and "updatedDate" have a description of "Deprecated" in the [developer documentation](https://s3.amazonaws.com/foliodocs/api/mod-users/p/users.html). My interpretation of that is that these fields should no longer be used because the developers plan to remove them at some point.

I think created_date and updated_date in users__t are coming from those deprecated top-level fields and not the metadata object, but we could check with @nassibnassar to be sure. If/when metadb starts unpacking nested objects, we may not need to use the jsonb_extract... to pull things from the metadata object, but I think for now we do.

**Comment by eliana-flo** [comment]
Gotcha, easy enough. I can add a comment to my SQL so we know what's going on.
