### ISSUE TITLE
RM/ERM - Create derived table: finance_invoice_transactions

### ISSUE THREAD

**Issue by stdombek** [folio-org/folio-analytics#517]
Create a derived table of fund distribution in invoices. The derived table contains the information on the fund distribution from the invoices app as well as from the transactions system table. The table is required to create reports with a GUI in reporting software solutions.

Database: MetaDB

**Comment by adoerrer** [comment]
Let's reopen this issue since invoice_transactions was identified as deprecated version of [finance_transaction_invoices.sql](https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/derived_tables/finance_transaction_invoices.sql)
