### ISSUE TITLE
Port instance_alternative_titles derived table to Metadb

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#525]
The original [instance_alternative_titles](https://github.com/folio-org/folio-analytics/blob/main/sql/derived_tables/instance_alternative_titles.sql) derived table is for LDP 1.x.  Porting it to Metadb might look something like
```sql
SELECT
    id,
    jsonb_extract_path_text(titles.jsonb, 'alternativeTitle') AS alternative_title,
    jsonb_extract_path_text(titles.jsonb, 'alternativeTitleTypeId')::uuid AS alternative_title_type_id,
    titles.ordinality
FROM
    folio_inventory.instance
    CROSS JOIN LATERAL jsonb_array_elements(jsonb_extract_path(jsonb, 'alternativeTitles')) WITH ORDINALITY
        AS titles (jsonb);
```
With the addition of the HRID and (via a join to inventory alternative title types) the type name.

**Comment by jenmawe** [comment]
Thanks for the help on this one. I also solved the issue that I was having with an array with no subproperties. I took inspiration from the LDP instance_editions derived table. Here

editions.data #>> '{}' AS edition,
    editions.ordinality AS edition_ordinality

I incorporated something similar in my test metadb derived instance ext table.
