### ISSUE TITLE
RM - port invoice_transactions to Metadb

### ISSUE THREAD

**Issue by adoerrer** [folio-org/folio-analytics#531]

**Comment by adoerrer** [comment]
Will not port this query due the successor of this query is `finance_transaction_invoices.sql` see [commit ](https://github.com/folio-org/folio-analytics/commit/7507667446cacbe6b40dc6f3e93667cda4ab8c56) The remaining query is only to drop `invoice_transactions ` derived if it ever existed. This has impact to the closed issue #517

**Comment by nassibnassar** [comment]
@adoerrer I think it is still needed for now to clean up an old version of the table.
