### ISSUE TITLE
MM - update LDP1 derived tables for Orchid data model changes

### ISSUE THREAD

**Issue by amzoss** [folio-org/folio-analytics#726]
- https://folio-project.slack.com/archives/C210RP0T1/p1672757167354339
- https://issues.folio.org/browse/MODQM-276
- We have derived tables for both subjects and series
- The current tables should still work, since they unpack the arrays; actually pulling the fields out of the new objects would be an extra step

**Comment by wafschneider** [comment]
I think `instance_series` was resolved by commit b096e38, and `instance_subject` was resolved by 64032cf, so perhaps this can be closed?

**Comment by amzoss** [comment]
Fine with me! I see these tables only extract the `value` field and not `authorityId`, but I'm fine closing this issue.
