### ISSUE TITLE
D-Reporting - Port Rpt ERM-Inventory Count Cluster to Metadb

### ISSUE THREAD

**Issue by stdombek** [folio-org/folio-analytics#746]
We need to port the "ERM-Inventory Count Cluster" rpt to Metadb when the required derived tables are ported.

Cluster for LDP1:
https://github.com/folio-org/folio-analytics/blob/main/sql/report_queries/erm/count/erm_inventory_count.sql

**Comment by stdombek** [comment]
blocked by #772

**Comment by sbeltaine** [comment]
Question:
Are we still supporting report queries moving forward? Aren't we moving reports to the wiki?

**Comment by stdombek** [comment]
The porting is necessary for the DBS.
