### ISSUE TITLE
ERM - Bugfix Rpt. Agreement fund distribution by fiscal years

### ISSUE THREAD

**Issue by stdombek** [folio-org/folio-analytics#752]
The report "[Agreement fund distribution by fiscal years](https://github.com/folio-org/folio-analytics/blob/1fb22c9e016ce892e2b3e1fb46b5432255045d2b/sql_metadb/report_queries/erm/agreement_fund_distribution_by_fiscal_years/erm_agreement_fund_distribution_by_fiscal_years.sql)" uses the derived table "finance_po_inv_transactions" that no longer exists. The required data can be generated elsewhere.

**Comment by thecomputerfella** [comment]
Hey @stdombek 
I would like to contribute towards this, could you please suggest which table should be replaced by 'finance_po_inv_transactions'.

**Comment by stdombek** [comment]
Hello @thecomputerfella , that's a good question. The derived table was originally intended to display po lines and invoice lines in one table. Unfortunately, this is not possible due to business logic. Cross products can arise and a 1:1 relation cannot be guaranteed. The approach could be only to use the level of transactions and here only the ones from invoices. The fund distribution could be a challenge.
Would you like to work on this issue? Then I would assign you to the issue.

**Comment by thecomputerfella** [comment]
So from which table should we derive the columns - invoice_line_fiscal_year_id, invoice_line_fiscal_year, invoice_line_fund_code, invoice_line_transaction_amount. Could you please tell me more about it,  before i take up this challenge.

**Comment by stdombek** [comment]
Explaining that takes a lot of time. I would therefore suggest that you attend one of our next meetings. We would be happy to explain the data model and the relations to you. Unfortunately, we have not yet created any meaningful documentation of these relationships. But we are working on it.
