### ISSUE TITLE
RA/UM - change date fields from text to timestamptz on feesfines_account_actions derived table for LDP1

### ISSUE THREAD

**Issue by sbeltaine** [folio-org/folio-analytics#760]
The following date fields on the feesfines_account_actions derived table need to be cast as timestamptz instead of text to match the source field coming from the public table: dateCreated, dateUpdated, and dateAction. 

When this derived table is used in a query, the incorrect field types (incorrectly) show time differences between the FOLIO system record and the report output for that record coming from LDP1. The fields are extracted from the JSON data array.

**Comment by amzoss** [comment]
Hi @sbeltaine! Just a reminder that we already have an issue for this derived table: #501

**Comment by sbeltaine** [comment]
The changes requested on this issue have been added to #501 , so I am closing this issue.
