### ISSUE TITLE
ERM - Create derived table 'openaccess_works' for Metadb

### ISSUE THREAD

**Issue by stdombek** [folio-org/folio-analytics#787]
The purpose of this derived table is to show informations about the records in the table "folio_oa.works" and their linked tables and reference data.
Attributes: https://wiki.folio.org/pages/viewpage.action?pageId=118272746

**Comment by stdombek** [comment]
@nayaldivya You are very welcome to work on it. :-)

**Comment by nayaldivya** [comment]
Hi @stdombek, Few questions:

- The derived table will be created under 'folio_reporting' and base tables to create this derived table is coming from 'folio_oa' correct?
- Where can I find the DDLs for base tables?

**Comment by stdombek** [comment]
- Derived tables are stored under the schema `folio_reporting` in Metadb
- All data for the derived tables come from the schemas and their tables for the different FOLIO apps. In Metadb the schema names starts with the prefix 'folio_'. You can find the data in various forms in different types of tables (see manual of Metadb: https://metadb.dev/doc/).

Example table name | Table type | Description
-- | -- | --
patrongroup__ | Main table | Current and historical records
patrongroup | Current table | Current records only
patrongroup__t__ | Main transformed table | Transformed versions of the records in patrongroup__
patrongroup__t | Current transformed table | Transformed versions of the records in patrongroup

- We have test data for open access. Unfortunately, the streaming process from the FOLIO database to Metadb still needs to be adjusted so that all tables and their data are transferred. It is therefore possible that not all required tables are available yet.
- DDL: You can see the relations very well in the FOLIO database, but not with Metadb. At the moment, we are creating documentations in the FOLIO project wiki ([https://wiki.folio.org/display/RPT/Open+Access+Reporting](https://wiki.folio.org/display/RPT/Open+Access+Reporting)) and also in the wiki of this repository together with the SME. 

You are very welcome to join our working group to find out more. There are no obligations associated with it. See more informations for that here [https://wiki.folio.org/display/RPT/Query+Development+Meetings](https://wiki.folio.org/display/RPT/Query+Development+Meetings) (Electronic Resource Management)

**Comment by nayaldivya** [comment]
Thanks @stdombek. One more question, the column names in the derived tables are going to be as it is as taken from base table? 
For eg; w_id coming from folio_oa.work will be w_id only in openaccess_work table or should i give some alias to it like oa_id?
