### ISSUE TITLE
ERM/ACQ - Add expense class to derived table "finance_invoice_transactions.sql"

### ISSUE THREAD

**Issue by stdombek** [folio-org/folio-analytics#791]
In FOLIO it is possible to select a fund several times within the fund distribution in an invoice line if the expense class is different. In order for the derived table "[finance_invoice_transactions.sql](https://github.com/folio-org/folio-analytics/blob/92b62956e3149ef4c1f2e5f2857ffce6eec7ff76/sql_metadb/derived_tables/finance_invoice_transactions.sql)" to work properly, this functionality must be added to the SQL statement.

**Comment by sbeltaine** [comment]
Requested updates to this derived table:
add expense class name and code as well as the external account number extension from the transactions table and the expense class table

**Comment by stdombek** [comment]
Please note: This is the perspective of invoices on transactions. This is necessary if you want to see all invoices without depending on their workflow status. The transactions can be NULL. The fund distribution can be assigned correctly. However, as soon as expense classes are added, the relation between fund distribution and transaction is no longer 1:1. Therefore, the expense class must be built into the logic.
