### ISSUE TITLE
MM fix for instance_publication derived table

### ISSUE THREAD

**Issue by natalyapik** [folio-org/folio-analytics#795]
need to add ordinality to the cross join 
CROSS JOIN jsonb_array_elements((i.data #> '{publication}')::jsonb) WITH ORDINALITY AS publication(data)

**Comment by sbeltaine** [comment]
Both the LDP and Metadb versions of the instance_publication derived tables have been updated for this change and published as of version 1.7.9 of folio-analytics derived tables.
