### ISSUE TITLE
Create Metadb report to output folio_finance.budget__t with calculated fields

### ISSUE THREAD

**Issue by nassibnassar** [folio-org/folio-analytics#827]
The table `folio_finance.budget__t` contains fields that are placeholders for data normally calculated by the business logic module.  This issue proposes creating a report that outputs the same schema as `folio_finance.budget__t` but with the calculated fields filled in.

Once completed, this report can be backported to a LDP derived table; see https://github.com/folio-org/folio-analytics/issues/828

**Comment by sbeltaine** [comment]
A new finance budget derived table has been created and merged as #864 
Closing issue.
