### ISSUE TITLE
fix loans_renewal_dates derived table for LDP

### ISSUE THREAD

**Issue by VandanaShah-Cornell** [folio-org/folio-analytics#852]
-- Changes to query: 
	-- truncated the renewal date ("created date") to 'minutes' to eliminate renewals seconds apart, which are artifacts of system processes, not actual patron renewals.
	-- added the item hrid
	-- selected the loan status from the circulation_loans table, not the circulation_loan_history table (which always shows "Open" for renewals)
	-- removed the loan history id ("id") from Select statement, since including it would make it impossible group by loan_id and count renewals
	-- removed the "loan_renewal_count" field (selected from the circulation_loan_history table) to prevent misuse of the field in calculating total renewals over a date range.
	-- cast the truncated date as "timestamptz"

**Comment by sbeltaine** [comment]
Closing. PR #853 resolves this issue.
