### ISSUE TITLE
Fix Metadb derived table loans_renewal_dates

### ISSUE THREAD

**Issue by VandanaShah-Cornell** [folio-org/folio-analytics#854]
-- Corrections:
	-- 1. changed source table to "folio_circulation.audit_loan" 
	-- 2. linked to "folio_circulation.loan" table to get actual loan status
	-- 3. truncated the seconds from the renewal date to eliminate false renewal counts
	-- 4. added the item hrid
	-- 5. renamed "renewal_count" to "folio_renewal_count" (can be used to sum renewals over a date range)
	-- 6. eliminated the "loan_renewal_count" field, since that is a very misleading figure and must not be used to sum renewals over a date range

**Comment by sbeltaine** [comment]
Closing issue, which was merged 7/7/24 as PR #855
