### ISSUE TITLE
Fix Metadb derived table holdings_ext

### ISSUE THREAD

**Issue by VandanaShah-Cornell** [folio-org/folio-analytics#856]
1. Fixed to bring in the correct data for the 'updated_by_user_id' field; it was bringing in data from the created by userid rather than the updated_by_user_id. 
2. The holdings_supress field needed to be cast as Boolean. 
3. The json extract for ill_policy_id needed to be cast as UUID.
4. Cast the date fields as "timestamptz" (changed from text)
5. Cast the discovery_suppress field as Boolean (changed from text)
6. Cast the extract of updatedByUserId as UUID (changed from text)

**Comment by sbeltaine** [comment]
Merged
