### ISSUE TITLE
Incorrect join in electronic access derived tables

### ISSUE THREAD

**Issue by amzoss** [folio-org/folio-analytics#92]
In [https://github.com/folio-org/folio-analytics/blob/master/sql/derived_tables/holdings_electronic_access.sql](holdings_electronic_access.sql), the relationship id from the electronic access object is being joined to inventory_instance_relationship_types. Is it possible it should join to inventory_electronic_access_relationships instead? @nassibnassar

**Comment by nassibnassar** [comment]
Yes, you are right.  This probably applies also to instances_electronic_access and items_electronic_access.
